### ISSUE TITLE
Wrong survey ID runnin test suite

### ISSUE THREAD

**Issue by Natureshadow** [sdaps/sdaps#119]
While packaging for Debian, I get the following errors running the test suite:

```
22c22
< survey_id = 143062700
---
> survey_id = 2251012651
22c22
< survey_id = 3751077550
---
> survey_id = 2251012651
None of the info files match for test-tex-ids!
```

It seems to be the last step of the test suite. The numbers remain the same in every run. Do they ring a bell?

**Comment by benzea** [comment]
Uh, you are running the stable release there? I have probably not added those IDs to the testsuite.

The issue is, that sometimes TeXLive changes in ways that modify the document in minute ways, and then things start to break. Unfortunately, there is little to do, other than telling people to be careful and simply adding the mismatching IDs to the tests …

**Comment by Natureshadow** [comment]
OK… Simply adding the "wrong" data to the reference set seems a bit contradictory to the purpose of testing, though ;)…

I think I will instead ignore the survey ID in the test for now.

As for the "stable release" thing: I could as well package 1.9.1. Is it backwards-compatible in that surveys printed with 1.2.1 can still be read back in 1.9.1?

**Comment by benzea** [comment]
I added a bit of code, so what you can now do is:
```
export IGNORE_PATTERN_EXTEND='\|^survey_id'
``'
which will cause the survey ID changes to be ignored.
