### ISSUE TITLE
How to insert an image inside a questionnaire

### ISSUE THREAD

**Issue by almasou** [sdaps/sdaps#167]
Hello,

I need to insert images inside a questionnaire but I don't know how to do it! I don't even know if is possible to do that with SDAPS.

The nearest I have found in documentation is _[Is it possible to put content inside a freeform textbox?](https://sdaps.org/FAQ/#is-it-possible-to-put-content-inside-a-freeform-textbox)_. But I don't know how to reference the image file.

Is it possible to insert images inside a SDPAS questionnaire? If yes, how? An example would be welcome!

Thanks.

**Comment by jdanion** [comment]
\documentclass[
  ......

**\usepackage{graphicx}
\graphicspath{ {/pathtoimage/} }**

....

\ExplSyntaxOn
\sdaps_overrides_init:n{
    % For all questoinnaires independent of their ID
     
**textboxvarname={centered_text={\includegraphics[scale=0.8]{graphiquename}}},**
    
    },
}
\ExplSyntaxOff

\begin{document}
...

\textbox[var=**textboxvarname**]{12.00000cm}{}

...
\end{document}

**Comment by almasou** [comment]
Thanks jdanion for this fast answer, but it doesn't works, it fails to compile and questionnaire.log shows _! LaTeX Error: Missing \begin{document}._ error.

Could you post a complete example that works?

**Comment by jdanion** [comment]
Ok this is one of the file i'm working on, it's in french :)

The picture is in the second page, it is designed to make an operating report

[CROFID.tex.zip](https://github.com/sdaps/sdaps/files/3040022/CROFID.tex.zip)
And the picture is name schema_postop.png

**Comment by almasou** [comment]
Thanks again.

I took your file and change the line `\graphicspath{ {/Users/jdanion/Google_Drive/SDAPS/Projets/} }` to my correct path, and then I renamed my image to `schema_postop`, but it still doesn't compile.

I attach the questionnaire.log file because I am unable to understand it.

Maybe something else is required...
[questionnaire.log](https://github.com/sdaps/sdaps/files/3040126/questionnaire.log)

**Comment by jdanion** [comment]
Remove

`%\textbox{0cm}{}
\myquestionbegin{barcode}{text}{text}
\mysettextboxtype{codebox}


% Note that we use hspace + vrule for sizing here, that is a bit weird but
% a reasonable method of setting a size
\mytexthbox{}{1bp}{ \hspace{5.8cm} \vrule width 0pt height 3.8cm depth 0cm }
\myquestionend{barcode}`

**Comment by almasou** [comment]
I have remove these lines but it still fails.

I attach the new questionnaire.log

[questionnaire.log](https://github.com/sdaps/sdaps/files/3040166/questionnaire.log)

**Comment by jdanion** [comment]
Ok it seems that you don't have the last release,

Remove choicequestions with "angle" argument

Or remove all questions but the textbox with the picture :)

**Comment by benzea** [comment]
/me notes that the `--add` option to the `setup` command allows copying the file into the project directory.

**Comment by almasou** [comment]
> Ok it seems that you don't have the last release,
> 
> Remove choicequestions with "angle" argument
> 
> Or remove all questions but the textbox with the picture :)

Thanks jdanion, this way it compiles and now I can show the image.




> /me notes that the `--add` option to the `setup` command allows copying the file into the project directory.

I don't understand what you mean benzea, could you explain further?


Well, now I can insert an image, but... is it possible to insert multiple images as options? For example, in a choicequestion, one image for each choiceitem.

I have made several tries without success. Any example on this?

**Comment by benzea** [comment]
I understand that a minimal example would be really useful. In general, you can use the normal LaTeX mechanisms to use images. All you need to do is make sure the image is readable when you create the SDAPS project (e.g. using the `--add` option to get it copied in or some other way as @jdanion did).

One thing that can also be useful is the `text` optional parameter, so that you will have proper metadata for those questions (rather than some obscure image text).

**Comment by almasou** [comment]
First of all, sorry if my questions are senseless, but I am totally novice with latex and I am just now beginning with SDAPS. Ah, and my english is a bit poor too.

1) @benzea I think you mean that using `--add` option with the `setup_tex` command the images are copied into the project folder and this way I don't need to specify `\graphicspath{ {/pathtoimage/} }` inside .tex file. Is this correct?
2) Should I use it like this `sdaps project_name setup_tex --add /path/to/imagefile.png questionnaire.tex`?
3) Is there any benefit in using `--add` option instead of `\graphicspath{ {/pathtoimage/} }`other than the images are copied to the project directory?

4) I want to achieve something like this:
![original](https://user-images.githubusercontent.com/45774079/55690519-17732f00-5993-11e9-836e-749e949c7e48.png)
but until now I only achieved this two options:
![untilnow](https://user-images.githubusercontent.com/45774079/55690574-9ec0a280-5993-11e9-8c95-490df6f10c19.png)
In the first option, the last image shows lower down than the others.
In the second one, the checkbox is still on top of the images and I find it unclearer than the original questionnarie.
Is it possible to achieve a questionnarie like the original one using sdaps?

Thanks.

**Comment by benzea** [comment]
1. Yes
2. Yeah, something like that
3. Nah, just a different method of achieving the same thing basically.
4. This is just for metadata. i.e. you are placing an image + text into the document, but maybe in the report (if you use that), you just want numbers "1-5" or "nada/not at all", … You can achieve that by doing something like `\choiceitem[text={nada/not at all}]{other text with graphcis}`. You may actually need to do this because that enables certain features to be used.

The best idea I have is to place everything into a `raisebox`. By moving the image, etc. up, you can effectively move the checkboxes down. That could improve the situation a lot.

In the end, there isn't really a way to do what you want here. It is technically possible obviously, but SDAPS does not provide any convenience, and you would need to do a lot of the stuff manually (see custom layout section of the class documentation; though I wouldn't recommend that for a novice to be honest).

**Comment by benzea** [comment]
I added an FAQ into the sphinx documentation. See https://sdaps.org/class-doc/FAQ.html#how-can-one-use-images
