### ISSUE TITLE
Listing of bugs found in the demo instance

### ISSUE THREAD

**Issue by TheRadialActive** [sdaps/sdaps#170]
We'll collect those bugs here, so we later can create seperate issues to fix those.

* [Text overlapping](https://demo.sdaps.org/surveys/75)
* [Many things defined didn't come up in the resulting pdf](https://demo.sdaps.org/surveys/100)

**Comment by benzea** [comment]
Hmm, as I see it:
 
1. This is a bug with multicols, not sure if we can even do anything
2. The problem here is that the user added a shitton of choices to one question, breaking things. What we can do here is add support for rotated headers to the webinterface, but I fear we won't be able to do something magical to prevent this.

**Comment by benzea** [comment]
Note that 2. will be a lot better once I upgrade SDAPS, because then the following questions will stop being broken.

**Comment by benzea** [comment]
Not sure what I was thinking back then. Really, IIRC, there was never anything actionable here (except maybe improving the feature set supported by the web frontend).
