### ISSUE TITLE
Segmentation Fault 11 on Recognize

### ISSUE THREAD

**Issue by diego-salvatierra** [sdaps/sdaps#53]
Hi, I am trying to use SDAPS on Mac OS X Mavericks. I managed to install it using Brew and Conda packages (not MacPorts) and got it to run. It works fine until the "recognize" command, when I get an unexplained Segfault 11 error. 

I tried reinstalling SDAPS using MacPorts to try a different Python and got to the same step, same segfault error. I'm new to computing, open-source, and python in general. Any help would be much appreciated! 

---
## \- SDAPS -- recognize

5 sheets
Segmentation fault: 11                                           |   0% --:--:--

**Comment by Xachriel** [comment]
Hi,

Start python and check does "import zbar" work, for me it gave Segfault 11 error.
There's some manual fixing involved: 
http://stackoverflow.com/questions/21612908/zbar-python-crashes-on-import-osx-10-9-1

Recognize worked, but the csv export didn't have any ids. Should it have? Recognize did output
Warning: Got a wrong survey ID (2.tif, 0)! It is 4199997583, but should be 2829233940. So zbar should be working.

**Comment by benzea** [comment]
Well, global_id and questionnair_id will be empty (they are only non-empty if there is a barcode printed on the paper).

That error is to be expected. You have an old version of the multicol package, which means that only the first example scan works. With newer versions of multicol/TeXlive only the second scan will work. The reason is that the layout changed slightly between the LaTeX versions.
